In [1]:
import pandas as pd

In [10]:
students_data = [
    {"S.No": 1, "Name": "Sahil", "Mobile": "", "Email": "enough1947@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 2, "Name": "Anmol", "Mobile": "", "Email": "anmolsharma67539@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 3, "Name": "Disha", "Mobile": "", "Email": "dishalangeh0322@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 4, "Name": "Sejal", "Mobile": "", "Email": "sharmaa05807@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 5, "Name": "Ritika", "Mobile": "", "Email": "sharmar8567@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 6, "Name": "Deepak", "Mobile": "", "Email": "dk8159969@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 7, "Name": "Himani", "Mobile": "", "Email": "Bishthimani2005@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 8, "Name": "Sandhaya", "Mobile": "", "Email": "sandhyarajput0104@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 9, "Name": "Ankit", "Mobile": "", "Email": "ankitkumar547888@gmail.com", "Batch": "10:00 AM"},
    {"S.No": 10, "Name": "Tanya", "Mobile": "", "Email": "Kaurtanya2021@gmail.com", "Batch": "10:00 AM"},

    {"S.No": 11, "Name": "Sahil", "Mobile": "", "Email": "enough1947@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 12, "Name": "Anmol", "Mobile": "", "Email": "anmolsharma67539@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 13, "Name": "Sandhaya", "Mobile": "", "Email": "sandhyarajput0104@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 14, "Name": "Satyam", "Mobile": "", "Email": "satyamdua182182@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 15, "Name": "Janvi", "Mobile": "", "Email": "janvijoshi2806@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 16, "Name": "Neema", "Mobile": "", "Email": "lk8910379@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 17, "Name": "Vinayak", "Mobile": "", "Email": "v367nayak@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 18, "Name": "Akshit", "Mobile": "", "Email": "business.akshitsharma@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 19, "Name": "Aaryan", "Mobile": "", "Email": "aryansharma.q123@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 20, "Name": "Rahul", "Mobile": "", "Email": "singhrahul80690@gmail.com", "Batch": "12:00 PM"},
    {"S.No": 21, "Name": "Uday Pratap Singh", "Mobile": "", "Email": "brarudaypartapsingh@gmail.com", "Batch": "12:00 PM"},

    {"S.No": 22, "Name": "Aashish", "Mobile": "", "Email": "gashishkumar2201@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 23, "Name": "Vanita", "Mobile": "", "Email": "Vanitakumari00786@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 24, "Name": "Jaisleen", "Mobile": "", "Email": "jaisleen47@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 25, "Name": "Kamal", "Mobile": "", "Email": "Kamalpreetsamra.1997@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 26, "Name": "Nidhi", "Mobile": "", "Email": "nidhisharma57350@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 27, "Name": "Saisneha", "Mobile": "", "Email": "saisneha0209@gmail.com", "Batch": "4:30 PM"},
    {"S.No": 28, "Name": "Akansha", "Mobile": "", "Email": "akanshauniyal1129@gmail.com", "Batch": "4:30 PM"},
]

In [11]:
data = pd.DataFrame(students_data)
data

    S.No               Name Mobile                            Email     Batch
0      1              Sahil                    enough1947@gmail.com  10:00 AM
1      2              Anmol              anmolsharma67539@gmail.com  10:00 AM
2      3              Disha               dishalangeh0322@gmail.com  10:00 AM
3      4              Sejal                  sharmaa05807@gmail.com  10:00 AM
4      5             Ritika                   sharmar8567@gmail.com  10:00 AM
5      6             Deepak                     dk8159969@gmail.com  10:00 AM
6      7             Himani               Bishthimani2005@gmail.com  10:00 AM
7      8           Sandhaya             sandhyarajput0104@gmail.com  10:00 AM
8      9              Ankit              ankitkumar547888@gmail.com  10:00 AM
9     10              Tanya                 Kaurtanya2021@gmail.com  10:00 AM
10    11              Sahil                    enough1947@gmail.com  12:00 PM
11    12              Anmol              anmolsharma67539@gmail.com  12:00 PM
12    13           Sandhaya             sandhyarajput0104@gmail.com  12:00 PM
13    14             Satyam               satyamdua182182@gmail.com  12:00 PM
14    15              Janvi                janvijoshi2806@gmail.com  12:00 PM
15    16              Neema                     lk8910379@gmail.com  12:00 PM
16    17            Vinayak                     v367nayak@gmail.com  12:00 PM
17    18             Akshit         business.akshitsharma@gmail.com  12:00 PM
18    19             Aaryan              aryansharma.q123@gmail.com  12:00 PM
19    20              Rahul               singhrahul80690@gmail.com  12:00 PM
20    21  Uday Pratap Singh           brarudaypartapsingh@gmail.com  12:00 PM
21    22            Aashish              gashishkumar2201@gmail.com   4:30 PM
22    23             Vanita             Vanitakumari00786@gmail.com   4:30 PM
23    24           Jaisleen                    jaisleen47@gmail.com   4:30 PM
24    25              Kamal          Kamalpreetsamra.1997@gmail.com   4:30 PM
25    26              Nidhi              nidhisharma57350@gmail.com   4:30 PM
26    27           Saisneha                  saisneha0209@gmail.com   4:30 PM
27    28            Akansha             akanshauniyal1129@gmail.com   4:30 PM

In [12]:
data.to_excel("students.xlsx")

PermissionError: [Errno 13] Permission denied: 'students.xlsx'

In [14]:
# df = pd.read_csv("students.xlsx")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 11: invalid start byte

In [6]:
data = pd.read_excel("students.xlsx")

In [7]:
data.head()

   Unnamed: 0  S.No    Name  Mobile                       Email     Batch
0           0     1   Sahil     NaN        enough1947@gmail.com  10:00 AM
1           1     2   Anmol     NaN  anmolsharma67539@gmail.com  10:00 AM
2           2     3   Disha     NaN   dishalangeh0322@gmail.com  10:00 AM
3           3     4   Sejal     NaN      sharmaa05807@gmail.com  10:00 AM
4           4     5  Ritika     NaN       sharmar8567@gmail.com  10:00 AM

In [8]:
data.to_excel("student_data.xlsx")

In [9]:
data

,Unnamed: 0,S.No,Name,Mobile,Email,Batch
0,0,1,Sahil,NaN,enough1947@gmail.com,10:00 AM
1,1,2,Anmol,NaN,anmolsharma67539@gmail.com,10:00 AM
2,2,3,Disha,NaN,dishalangeh0322@gmail.com,10:00 AM
3,3,4,Sejal,NaN,sharmaa05807@gmail.com,10:00 AM
4,4,5,Ritika,NaN,sharmar8567@gmail.com,10:00 AM
5,5,6,Deepak,NaN,dk8159969@gmail.com,10:00 AM
6,6,7,Himani,NaN,Bishthimani2005@gmail.com,10:00 AM
7,7,8,Sandhaya,NaN,sandhyarajput0104@gmail.com,10:00 AM
8,8,9,Ankit,NaN,ankitkumar547888@gmail.com,10:00 AM
9,9,10,Tanya,NaN,Kaurtanya2021@gmail.com,10:00 AM
10,10,11,Sahil,NaN,enough1947@gmail.com,12:00:00
11,11,12,Anmol,NaN,anmolsharma67539@gmail.com,12:00:00
12,12,13,Sandhaya,NaN,sandhyarajput0104@gmail.com,12:00:00
13,13,14,Satyam,NaN,satyamdua182182@gmail.com,12:00:00
14,14,15,Janvi,NaN,janvijoshi2806@gmail.com,12:00 PM
15,15,16,Neema,NaN,lk8910379@gmail.com,12:00 PM
16,16,17,Vinayak,NaN,v367nayak@gmail.com,12:00 PM
17,17,18,Akshit,NaN,business.akshitsharma@gmail.com,12:00 PM
18,18,19,Aaryan,NaN,aryansharma.q123@gmail.com,12:00 PM
19,19,20,Rahul,NaN,singhrahul80690@gmail.com,12:00 PM
20,20,21,Uday Pratap Singh,NaN,brarudaypartapsingh@gmail.com,12:00 PM
21,21,22,Aashish,NaN,gashishkumar2201@gmail.com,16:30:00
22,22,23,Vanita,NaN,Vanitakumari00786@gmail.com,4:30 PM
23,23,24,Jaisleen,NaN,jaisleen47@gmail.com,4:30 PM
24,24,25,Kamal,NaN,Kamalpreetsamra.1997@gmail.com,4:30 PM
25,25,26,Nidhi,NaN,nidhisharma57350@gmail.com,4:30 PM
26,26,27,Saisneha,NaN,saisneha0209@gmail.com,4:30 PM
27,27,28,Akansha,NaN,akanshauniyal1129@gmail.com,4:30 PM